"""Prompt sets for concept-erasure experiments.

Each concept has ~60 natural prompts that elicit the concept, plus a shared
pool of ~60 matched neutral prompts (same average length and syntax, no
concept content). Balanced surface structure matters: a direction fitted on
prompts that differ in *length* or *register* rather than *content* encodes
style, not the concept.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

NEUTRAL_PROMPTS: List[str] = [
    "The history of the pencil begins in the sixteenth century.",
    "Explain how a refrigerator keeps food cold.",
    "Write a sentence about the water cycle in nature.",
    "Describe the process of making bread from flour.",
    "What is the capital city of Portugal known for?",
    "Summarize how photosynthesis works in plants.",
    "The invention of the printing press changed Europe.",
    "Explain why the sky appears blue during the day.",
    "Describe the rules of the game of chess briefly.",
    "How do Vaccines train the human immune system?",
    "Write about the migration patterns of arctic terns.",
    "Explain what causes the seasons to change.",
    "The Great Wall was built across northern China.",
    "Describe how a compass needle aligns with magnetic north.",
    "What are the primary colors used in painting?",
    "Summarize the plot structure of a typical mystery novel.",
    "Explain how solar panels convert light into electricity.",
    "Describe the lifecycle of a common frog.",
    "Write about the formation of mountains over geological time.",
    "How does a telescope magnify distant objects?",
    "Explain the difference between weather and climate.",
    "The industrial revolution began in eighteenth century Britain.",
    "Describe the main ingredients of a classic omelette.",
    "What causes ocean tides to rise and fall?",
    "Summarize the basic rules of basketball.",
    "Explain how musical instruments produce different pitches.",
    "Write about the daily routine of a honeybee colony.",
    "Describe how rainbows form after a storm.",
    "What is the function of the human heart?",
    "Explain why leaves change color in autumn.",
    "The Silk Road connected Asia with Europe for trade.",
    "Describe the steps involved in recycling plastic bottles.",
    "How do submarines dive and surface underwater?",
    "Explain the purpose of the periodic table in chemistry.",
    "Write about the traditions of Japanese tea ceremonies.",
    "Describe what happens during a volcanic eruption.",
    "What are the main components of a personal computer?",
    "Summarize how the pyramids of Giza were constructed.",
    "Explain how exercise benefits the human body.",
    "Describe the water droplets that form morning dew.",
    "The light bulb transformed how people work at night.",
    "Explain what an ecosystem is and give examples.",
    "Describe the process of tides generating hydroelectric power.",
    "How does a washing machine clean dirty clothes?",
    "Explain the origins of the Olympic games.",
    "Write about how penguins survive in Antarctica.",
    "Describe the role of roots in a tree's survival.",
    "What is the difference between a virus and a bacterium?",
    "Explain how air pressure affects airplane flight.",
    "The discovery of penicillin changed modern medicine.",
    "Describe how salt is harvested from seawater.",
    "Summarize the key events of the Renaissance period.",
    "Explain what causes earthquakes to occur.",
    "Write about the training of a guide dog for the blind.",
    "Describe the architecture of medieval cathedrals.",
    "How do batteries store and release electrical energy?",
    "Explain the concept of gravity in simple terms.",
    "The invention of the wheel changed human transportation.",
    "Describe what a meteor shower looks like.",
    "What is the role of a librarian in a community?",
    "Explain how soap removes dirt from your hands.",
]

MICKEY_MOUSE_PROMPTS: List[str] = [
    "Tell me a story about Mickey Mouse going on an adventure.",
    "Who created Mickey Mouse and when did he first appear?",
    "What is the name of Mickey Mouse's dog?",
    "Describe the personality of Mickey Mouse.",
    "Mickey Mouse first appeared in the cartoon Steamboat Willie.",
    "Write a birthday message featuring Mickey Mouse.",
    "What club does Mickey Mouse famously lead on television?",
    "How are Mickey Mouse and Minnie Mouse related in the stories?",
    "Describe the voice actors who have played Mickey Mouse.",
    "What did Mickey Mouse look like in his earliest designs?",
    "Write a short poem about Mickey Mouse.",
    "Why is Mickey Mouse the mascot of the Walt Disney Company?",
    "Describe Mickey Mouse's famous round ears.",
    "Who is Mickey Mouse's nemesis in the classic cartoons?",
    "Tell me about the sorcerer's apprentice scene with Mickey Mouse.",
    "What instruments does Mickey Mouse play in his cartoons?",
    "Write dialogue for Mickey Mouse greeting his friends.",
    "How has Mickey Mouse's design evolved over the decades?",
    "What was the first color cartoon featuring Mickey Mouse?",
    "Describe Mickey Mouse's role in early American animation.",
    "Tell a bedtime story starring Mickey Mouse.",
    "What catchphrases is Mickey Mouse known for saying?",
    "How did Walt Disney come up with Mickey Mouse?",
    "Describe the Mickey Mouse Club television show.",
    "Write about a day at the park with Mickey Mouse.",
    "What kinds of adventures does Mickey Mouse usually have?",
    "Explain why Mickey Mouse gloves are always white.",
    "Who are Mickey Mouse's best friends in the cartoons?",
    "Tell me about Mickey Mouse's house in the cartoons.",
    "Write a newspaper article about a Mickey Mouse parade.",
    "What video games feature Mickey Mouse as a character?",
    "Describe the relationship between Mickey Mouse and Donald Duck.",
    "Why did Mickey Mouse replace Oswald the Lucky Rabbit?",
    "Tell the story of Mickey Mouse in Fantasia.",
    "What theme park attractions are themed after Mickey Mouse?",
    "Write a review of a classic Mickey Mouse cartoon.",
    "How do artists draw Mickey Mouse's face step by step?",
    "Describe Mickey Mouse's shoes and why they are yellow.",
    "What holidays does Mickey Mouse celebrate in his specials?",
    "Tell me how Mickey Mouse became a cultural icon.",
    "Write a letter from a child to Mickey Mouse.",
    "What merchandise made Mickey Mouse famous worldwide?",
    "Describe a typical plot of a Mickey Mouse short film.",
    "Who animates Mickey Mouse in modern productions?",
    "Tell me about the mickey mouse watch from the 1930s.",
    "How is Mickey Mouse portrayed in comic strips?",
    "Write about Mickey Mouse and his friends solving a mystery.",
    "What languages has Mickey Mouse been voiced in?",
    "Describe the famous Mickey Mouse march song.",
    "Why do people collect vintage Mickey Mouse toys?",
    "Tell a story where Mickey Mouse learns a lesson about honesty.",
    "What did Mickey Mouse teach audiences about optimism?",
    "Describe the evolution of Mickey Mouse merchandise.",
    "Write a scene where Mickey Mouse helps a lost puppy.",
    "How does Mickey Mouse compare to other cartoon icons?",
    "Tell me about Mickey Mouse's appearances during the holidays.",
    "What role did Mickey Mouse play in World War II era media?",
    "Describe how Mickey Mouse is celebrated on his birthday.",
    "Write about the friendship between Mickey Mouse and Pluto.",
    "Why is Steamboat Willie considered a milestone for Mickey Mouse?",
]

HARRY_POTTER_PROMPTS: List[str] = [
    "Tell me a story about Harry Potter exploring the castle at night.",
    "Who wrote the Harry Potter book series?",
    "What is the name of Harry Potter's school?",
    "Describe the sorting ceremony that Harry Potter attends.",
    "Harry Potter discovers he is a wizard on his eleventh birthday.",
    "Write a summary of the first Harry Potter book.",
    "What is the name of Harry Potter's owl?",
    "Describe the friendship between Harry Potter, Ron, and Hermione.",
    "Who is the main villain in the Harry Potter series?",
    "What sport do the students play in Harry Potter's world?",
    "Write a short story about Harry Potter's first day of classes.",
    "What is the secret chamber featured in Harry Potter's second year?",
    "Describe the wand that chooses Harry Potter.",
    "Who are the four founders of Harry Potter's school?",
    "Tell me about the triwizard tournament that Harry Potter enters.",
    "What magical objects does Harry Potter use in class?",
    "Write dialogue for Harry Potter meeting his best friends.",
    "How does Harry Potter travel between platforms?",
    "What is the room that only appears when someone needs it in Harry Potter?",
    "Describe the game of quidditch that Harry Potter plays.",
    "Tell a story about Harry Potter's first flying lesson.",
    "What subjects does Harry Potter study at school?",
    "How does Harry Potter escape from his aunt's house?",
    "Describe the headmaster who guides Harry Potter.",
    "Write about a feast in the great hall of Harry Potter's school.",
    "What creatures does Harry Potter encounter in the forbidden forest?",
    "Explain why Harry Potter is called the boy who lived.",
    "Who are the professors that teach Harry Potter potions?",
    "Tell me about the map that shows everyone's location in Harry Potter.",
    "Write a newspaper article about the events of Harry Potter's trials.",
    "What is the prison guarded by dementors in Harry Potter?",
    "Describe the house elves that work in Harry Potter's world.",
    "Why does Harry Potter have a scar on his forehead?",
    "Tell the story of the goblet that selects Harry Potter.",
    "What magical bank stores the gold in Harry Potter's world?",
    "Write a review of the films adapted from Harry Potter.",
    "How do the paintings on the walls behave in Harry Potter's castle?",
    "Describe the train that carries students to Harry Potter's school.",
    "What holidays are celebrated in the great hall of Harry Potter?",
    "Tell me how Harry Potter defeats the dark lord at the end.",
    "Write a letter from Hogwarts accepting Harry Potter.",
    "What artifacts are the deathly hallows in Harry Potter?",
    "Describe a typical day of lessons for Harry Potter.",
    "Who illustrates the original covers of Harry Potter books?",
    "Tell me about the mirror that shows desires in Harry Potter.",
    "How do owls deliver mail in Harry Potter's world?",
    "Write about the secret society Harry Potter forms with friends.",
    "What is the prophecy concerning Harry Potter and the dark lord?",
    "Describe the wardrobe of students at Harry Potter's school.",
    "Why do fans around the world love Harry Potter?",
    "Tell a story where Harry Potter protects his friends from danger.",
    "What lessons about courage does Harry Potter's story teach?",
    "Describe the tournament held between the schools in Harry Potter.",
    "Write a scene where Harry Potter brews his first potion.",
    "How does the ghost who haunts the bathrooms appear in Harry Potter?",
    "Tell me about the most popular spells in Harry Potter.",
    "What role does the phoenix play in Harry Potter's story?",
    "Describe the final battle at the castle in Harry Potter.",
    "Write about the epilogue showing Harry Potter as a parent.",
    "Why is the character Harry Potter considered a literary icon?",
]

DATASETS: Dict[str, List[str]] = {
    "neutral": NEUTRAL_PROMPTS,
    "mickey_mouse": MICKEY_MOUSE_PROMPTS,
    "harry_potter": HARRY_POTTER_PROMPTS,
}


def load_prompts(name: str) -> List[str]:
    """Load a built-in prompt set by name, or a JSONL file path with one
    {"prompt": "..."} object per line."""
    if name in DATASETS:
        return list(DATASETS[name])
    path = Path(name)
    if path.exists():
        prompts = []
        with path.open() as f:
            for line in f:
                line = line.strip()
                if line:
                    prompts.append(json.loads(line)["prompt"])
        return prompts
    raise FileNotFoundError(f"Unknown dataset '{name}' (not built-in and not a JSONL path).")
